version: '3.8'

services:
  ros:
    user: ${ROS_USER}
    env_file:
      - .env
    network_mode: host
    build:
      context: .
      network: host
      dockerfile: ./docker/Dockerfile
      args:
        UBUNTU_DISTRO: focal
        ROS_DISTRO: noetic
        USER: ${ROS_USER}
      secrets:
        - ssh_key
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/home/${ROS_USER}/catkin_ws/src
    stdin_open: true
    tty: true

secrets:
  ssh_key:
    file: /home/${USER}/.ssh/id_ed25519
