services:
  ros:
    user: ${ROS_USER}
    env_file:
      - .env
    network_mode: host
    build:
      context: .
      network: host
      dockerfile: ./docker/Dockerfile
      args:
        UBUNTU_DISTRO: focal
        ROS_DISTRO: noetic
        USER: ${ROS_USER}
      secrets:
        - ssh_key
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [ gpu ]
    # devices:
    #   - "/dev/ttyACM0:/dev/ttyACM0" # Specify your Arduino device here
    privileged: true
    volumes:
      - ./src:/home/${ROS_USER}/catkin_ws/src
      - ./config:/home/${ROS_USER}/catkin_ws/config
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    stdin_open: true
    tty: true
    device_cgroup_rules:
      - "c 81:* rmw"
      - "c 189:* rmw"

secrets:
  ssh_key:
    file: /home/${USER}/.ssh/id_ed25519
