width_target: 0.4
height_target: 0.35

flow_radius: 0.03
limit_cycle_radius: 0.03
limit_cycle_speed: 6
conv_rate: 10

linear_speed: 0.04

robot_name: "ur5"
toolOffsetFromTarget: 0.9

toleranceToNextPoint: 0.15