# shotcrete: 

flowRadius: 0.03
limitCycleRadius: 0.03
limitCycleSpeed: 9
convRate: 10
linearSpeed: 0.05
toolOffsetFromTarget: 0.7
toleranceToNextPoint: 0.1
velocityLimit: 1.5

# surface_finishing: 

#   flowRadius: 0.03
#   limitCycleRadius: 0.03
#   limitCycleSpeed: 3 
#   convRate: 2 
#   linearSpeed: 0.05
#   toolOffsetFromTarget: 0.1
#   toleranceToNextPoint: 0.1
#   velocityLimit: 1.5




