# Configuration to be used for the different tasks.
# Possible robot_name to set, depending on the task :
# - Iiwa7
# - Ur5
# - Cr7
# - Cobod
# Tristan Bonato : 2024-03-15

shotcrete:
  # robot_name: "ur5_robot"
  robot_name: "iiwa7"
surface_finishing:
  # robot_name: "iiwa7"
  robot_name: "ur5_robot"
metal_additive:
  robot_name: "xMateCR7"
